export default function Page() {
    return (
		<main>
		<h1>Privacy Policy</h1>
		<p><i>Last updated: June 16, 2020</i></p>

		Protecting the privacy of your data is important to us at ChartInsight LLC (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;). We operate the <a href="https://chartinsight.com">https://chartinsight.com</a> website (the &quot;Service&quot;). This policy outlines: what data we collect and why; how your data is handled; and your rights to your data.

		<h2>What we collect and why</h2>
		<p>We only collect what we need to enable personalized use of chartinsight.com. We promise to <b>never sell or share your data</b>.</p>

		<h3>Identity and access</h3>
		<p>When you sign up for ChartInsight, we ask for your email address and send you a verification link so we know that you a human instead of a robot. We&apos;ve put thousands of hours of work into ChartInsight and don&apos;t want a robot copying it. We will never sell your email address.</p>

		<p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>

		<p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our <a href="/about/terms">Terms of Service</a>.</p>

		<h2>Definitions</h2>
		<ul>
			<li>
				<p><b>Service</b> is the <a href="https://chartinsight.com">https://chartinsight.com</a> website operated by ChartInsight LLC</p>
			</li>
			<li>
				<p><b>Personal Data</b> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
			</li>
			<li>
				<p><b>Usage Data</b> is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
			</li>
			<li>
				<p><b>Cookies</b> are small pieces of data stored on your device (computer or mobile device).</p>
			</li>
			<li>
				<p><b>Data Controller</b> means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
				<p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>
			</li>
			<li>
				<p><b>Data Processors (or Service Providers)</b> means any natural or legal person who processes the data on behalf of the Data Controller.</p>
				<p>We may use the services of various Service Providers in order to process your data more effectively.</p>
			</li>
			<li>
				<p><b>Data Subject (or User)</b> is any living individual who is using our Service and is the subject of Personal Data.</p>
			</li>
		</ul>

		<h2>Information Collection and Use</h2>
		<p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

		<h3>Types of Data Collected</h3>
		<h4>Personal Data</h4>
		<p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&quot;Personal Data&quot;). Personally identifiable information may include, but is not limited to:</p>

		<ul>
			<li>Email address</li>
			<li>First name and last name</li>
			<li>Phone number</li>
			<li>Address, City, ZIP/Postal code, State/Province, Country</li>
			<li>Cookies and Usage Data</li>
		</ul>
		<p>We may use your Personal Data to contact you with notifications, newsletters and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.</p>
		<h4>Usage Data</h4>
		<p>We may also collect information how the Service is accessed and used (&quot;Usage Data&quot;). This Usage Data may include information such as your computer&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

		<h4>Tracking &amp; Cookies Data</h4>
		<p>We use cookies and similar tracking technologies to track the activity on our Service and enable people to stay logged in with personalized settings.</p>

		<p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
		<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
		<p>Examples of Cookies we use:</p>
		<ul>
			<li><b>Session Cookies.</b> We use Session Cookies to operate our Service and allow you to stay logged in.</li>
			<li><b>Preference Cookies.</b> We use Preference Cookies to remember your preferences and various settings.</li>
		</ul>

		<h2>Use of Data</h2>
		<p>ChartInsight LLC uses the collected data for various purposes:</p>
		<ul>
			<li>To provide and maintain our Service</li>
			<li>To notify you about changes to our Service</li>
			<li>To allow you to participate in interactive features of our Service when you choose to do so</li>
			<li>To provide customer support</li>
			<li>To gather analysis or valuable information so that we can improve our Service</li>
			<li>To monitor the usage of our Service</li>
			<li>To detect, prevent and address technical issues</li>
			<li>To detect, prevent and address potential fraudulent use of our Service</li>
			<li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
		</ul>

		<h2>Your Data Subject Rights</h2>
		<p>If you provide us with Personally Identifiable Information, you have the right to access, edit, delete, or export (i.e. data portability), or object to or restrict certain categories of Personally Identifiable Information that you have supplied to us by contacting us in accordance with the information provided in the Contact Information section below. We will promptly review all such requests in accordance with applicable laws.</p>

		<h2>Legal Basis for Processing Personal Data</h2>

		<p>ChartInsight LLC legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>

		<p>ChartInsight LLC may process your Personal Data because:</p>
		<ul>
			<li>We need to perform a contract with you</li>
			<li>You have given us permission to do so</li>
			<li>The processing is in our legitimate interests and it&apos;s not overridden by your rights</li>
			<li>For payment processing purposes</li>
			<li>To comply with the law</li>
		</ul>

		<h2>Retention of Data</h2>
		<p>ChartInsight LLC will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

		<p>ChartInsight LLC will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

		<h2>Transfer of Data</h2>
		<p>Your information, including Personal Data, may be transferred to -- and maintained on -- computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
		<p>If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.</p>
		<p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
		<p>ChartInsight LLC will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

		<h2>Disclosure of Data</h2>
		<p>If the appropriate law enforcement authorities have the necessary warrant, criminal subpoena, or court order requiring we share data, we have to comply. Otherwise, we flat-out reject requests from local and federal law enforcement when they seek data. And unless we&apos;re legally prevented from it, we&apos;ll always inform you when such requests are made. <i>We have never received a National Security Letter or Foreign Intelligence Surveillance Act (FISA) order requesting information</i>.</p>

		<h3>Legal Requirements</h3>
		<p>ChartInsight LLC may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
		<ul>
			<li>To comply with a legal obligation</li>
			<li>To protect and defend the rights or property of ChartInsight LLC</li>
			<li>To prevent or investigate possible wrongdoing in connection with the Service</li>
			<li>To protect the personal safety of users of the Service or the public</li>
			<li>To protect against legal liability</li>
		</ul>

		<h2>Your Rights With Respect to Your Information</h2>
		At ChartInsight, we apply the same data rights to all customers, regardless of their location. Currently some of the most privacy-forward regulations in place are the European Union&apos;s General Data Protection Regulation (&quot;GDPR&quot;) and California Consumer Privacy Act (&quot;CCPA&quot;) in the US. We recognize all of the rights granted in these regulations, except as limited by applicable law. These rights include:

		<ul>
			<li><p><b>Right to Know.</b> You have the right to know what personal information is collected, used, shared or sold. We outline both the categories and specific bits of data we collect, as well as how they are used, in this privacy policy.</p></li>
			<li><p><b>Right of Access.</b> This includes your right to access the personal information we gather about you, and your right to obtain information about the sharing, storage, security and processing of that information.</p></li>
			<li><p><b>Right to Correction.</b> You have the right to request correction of your personal information.</p></li>
			<li><p><b>Right to Erasure / &quot;To be Forgotten&quot;.</b> This is your right to request, subject to certain limitations under applicable law, that your personal information be erased from our possession and, by extension, all of our service providers.</p></li>
			<li><p><b>Right to Complain.</b> You have the right to make a complaint regarding our handling of your personal information with the appropriate supervisory authority. To identify your specific authority or find out more about this right, EU individuals should go to <a target="_blank" href="https://edpb.europa.eu/about-edpb/board/members_en">https://edpb.europa.eu/about-edpb/board/members_en</a>.</p></li>
			<li><p><b>Right to Restrict Processing.</b> This is your right to request restriction of how and why your personal information is used or processed, including opting out of sale of personal information. (Again: we never have and never will sell your personal data).</p></li>
			<li><p><b>Right to Object.</b> You have the right, in certain situations, to object to how or why your personal information is processed.
		Right to Portability. You have the right to receive the personal information we have about you and the right to transmit it to another party.</p></li>
			<li><p><b>Right to not be subject to Automated Decision-Making.</b> You have the right to object and prevent any decision that could have a legal, or similarly significant, effect on you from being made solely based on automated processes. This right is limited, however, if the decision is necessary for performance of any contract between you and us, is allowed by applicable law, or is based on your explicit consent.</p></li>
			<li><p><b>Right to Non-Discrimination.</b> This right stems from the CCPA. We do not and will not charge you a different amount to use our products, offer you different discounts, or give you a lower level of customer service because you have exercised your data privacy rights. However, the exercise of certain rights (such as the right &quot;to be forgotten&quot;) may, by virtue of your exercising those rights, prevent you from using our Services.</p></li>
		</ul>

		<p>Many of these rights can be exercised by signing in and directly updating your account information.</p>

		<p>If you have questions about exercising these rights or need assistance, please <a target="_blank" href="https://chartinsight.com/about/contact">contact us</a>. For requests to delete personal information or know what personal information has been collected, we will first verify your identity using a combination of at least two pieces of information already collected including your user email address. If an authorized agent is corresponding on your behalf, we will first need written consent with a signature from the account holder before proceeding.</p>

		<p>If you are in the EU, you can identify your specific authority to file a complaint or find out more about GDPR, at <a target="_blank" href="https://edpb.europa.eu/about-edpb/board/members_en">https://edpb.europa.eu/about-edpb/board/members_en</a>.</p>

		<h2>Security of Data</h2>
		<p>All data is encrypted via SSL/TLS when transmitted from our servers to your browser. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

		<h2>Service Providers</h2>
		<p>We may employ third party companies and individuals to facilitate our Service (&quot;Service Providers&quot;), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>

		<p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

		<h3>Analytics</h3>
		<p>We use Google Analytics, a third-party Service Provider, to monitor and analyze the use of our Service. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</p>
		<p>You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.</p>
		<p>For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: <a target="_blank" href="https://www.google.com/intl/en/policies/privacy/">http://www.google.com/intl/en/policies/privacy/</a></p>

		<h3>Payments and Billing information</h3>
		<p>ChartInsight will always have a free version. You can choose to enhance the free version with a premium subscription. If you choose to pay for a premium subscription, we will use
		PayPal/Braintree to handle payment processing. We will not store or collect your payment card details. That information is provided directly to PayPal/Braintree whose use of your personal information is governed by their Privacy Policy (see <a target="_blank" href="https://www.paypal.com/webapps/mpp/ua/privacy-full">https://www.paypal.com/webapps/mpp/ua/privacy-full</a>). PayPal/Braintree adheres to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>

		<h3>Geolocation data</h3>
		<p>We log all access to all accounts by full IP address so we can always verify no unauthorized access has happened. We keep this login data for as long as necessary to improve the service.</p>

		<h2>Links to Other Sites</h2>
		<p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

		<h2>Children&apos;s Privacy</h2>
		<p>Our Service does not address anyone under the age of 18 (&quot;Children&quot;).</p>
		<p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children have ([or] Child has) provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

		<h2>Location of Our Servers; Governing Law and Venue for any Disputes</h2>
		<p>If you are using the Services from outside the United States, please be aware that the Services and the servers that host it are located in the United States and any information or data you provide, including Personally Identifiable Information, will be transferred to the United States. By using the Services or providing your Personally Identifiable Information, you agree and consent to (a) the application of the laws of Washington State, United States, with respect to any dispute arising out of or related to this Privacy Policy, and (b) the exclusive jurisdiction of the courts of Washington State, United States to resolve any such dispute and you hereby waive any objection thereto based on inconvenient forum.</p>

		<h2>Changes to This Privacy Policy</h2>
		<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
		<p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the &quot;effective date&quot; at the top of this Privacy Policy.</p>
		<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

		<h2>Contact Information</h2>
		<p>If you have any questions about this Privacy Policy, please <a target="_blank" href="https://chartinsight.com/about/contact">contact us</a></p>
		</main>
	);
}